### ISSUE TITLE
 上拉加载更多，UITableView 会有跳动，整体下拉然后在恢复

### ISSUE THREAD

**Issue by davieds** [CoderMJLee/MJRefresh#1044] opened 2017-11-17 11:44 UTC
上拉加载数据，加载完后，整个TableVIew会有跳动现象。

**Comment by xnxy** [comment] 2017-11-18 08:32
我也遇到……同问如何解决……

**Comment by Kaizi-oo** [comment] 2017-11-20 09:38
同=相同问题，而且 scrollToRow 方法无法让tableView滑动到最上面

**Comment by pusswzy** [comment] 2017-11-28 06:39
同问  是iOS 11才会有的问题

**Comment by davieds** [comment] 2017-11-28 07:14
iOS 8.0也会有的发自我的iPhone------------------ 原始邮件 ------------------发件人: pusswzy  <notifications@github.com>发送时间: 2017年11月28日 14:39收件人: CoderMJLee/MJRefresh <MJRefresh@noreply.github.com>抄送: davieds <yanruoxi.x@gmail.com>, Author <author@noreply.github.com>主题: 回复：[CoderMJLee/MJRefresh] 上拉加载更多，UITableView 会有跳动，整体下拉然后在恢复 (#1044)同问  是iOS 11才会有的问题

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CoderMJLee/MJRefresh","title":"CoderMJLee/MJRefresh","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CoderMJLee/MJRefresh"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pusswzy in #1044: 同问  是iOS 11才会有的问题"}],"action":{"name":"View Issue","url":"https://github.com/CoderMJLee/MJRefresh/issues/1044#issuecomment-347428534"}}}

**Comment by SuperLoveSue** [comment] 2017-12-06 09:23
遇到了相同问题 在iOS11下会有这样的问题

**Comment by davieds** [comment] 2018-01-29 03:26
好的，稍后尝试下你的方法发自我的iPhone------------------ 原始邮件 ------------------发件人: FancyHuang  <notifications@github.com>发送时间: 2018年1月24日 10:47收件人: CoderMJLee/MJRefresh <MJRefresh@noreply.github.com>抄送: davieds <yanruoxi.x@gmail.com>, Author <author@noreply.github.com>主题: 回复：[CoderMJLee/MJRefresh] 上拉加载更多，UITableView 会有跳动，整体下拉然后在恢复 (#1044)我这边也有出现过，原因是我把footer hidden了，所以出现了这个问题，只要不隐藏就好了

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CoderMJLee/MJRefresh","title":"CoderMJLee/MJRefresh","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CoderMJLee/MJRefresh"}},"updates":{"snippets":[{"icon":"PERSON","message":"@FancyHuang in #1044: 我这边也有出现过，原因是我把footer hidden了，所以出现了这个问题，只要不隐藏就好了"}],"action":{"name":"View Issue","url":"https://github.com/CoderMJLee/MJRefresh/issues/1044#issuecomment-360003314"}}}

**Comment by davieds** [comment] 2018-02-01 08:37
@FancyHuang 不行，iOS 8.0 系统版本，尝试footer hidden了，还是会有跳动的情况。

**Comment by FancyHuang** [comment] 2018-02-02 08:02
@davieds 哈哈，你可能理解错了，我出现跳动的原因是footer.hidden = YES; 然后我设置成 footer.hidden = NO 就不会出现这种情况了。没有8.0的，其他好像都不会出现跳动，我这边

**Comment by Gitool** [comment] 2018-10-31 07:58
已经解决。
参看[【已解决】iOS11使用MJRefresh上拉加载结束tableView闪动、跳动的问题](https://www.cnblogs.com/cchHers/p/9883646.html)

**Comment by wolfcon** [comment] 2019-06-27 10:16
Duplicate of #1009

PR is #1306 
Will launch in `3.3.0`

**Closed by wolfcon** 2019-06-27 10:16 UTC
