### ISSUE TITLE
iOS 上拉加载无限次访问后台服务器

### ISSUE THREAD

**Issue by WenzheFan** [CoderMJLee/MJRefresh#1113] opened 2018-02-05 11:28 UTC
iOS 上拉加载无限次访问后台服务器，导致阿里服务器老是内存溢出

**Comment by HughLi** [comment] 2018-03-05 03:45
try
if (@available(iOS 11.0, *)) {
            tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        }else {
            self.automaticallyAdjustsScrollViewInsets = NO;
        }
       tableView.estimatedRowHeight = 0;
        tableView.estimatedSectionHeaderHeight = 0;
        tableView.estimatedSectionFooterHeight = 0;

**Comment by wolfcon** [comment] 2019-06-27 10:22
Duplicate of #1009

PR is #1306 
Will launch in `3.3.0`

**Closed by wolfcon** 2019-06-27 10:22 UTC
