### ISSUE TITLE
滑到底部，再调用deleteRowsAtIndexPaths:withRowAnimation:然后底部的上拉控件就迅速地向上飘。。。

### ISSUE THREAD

**Issue by qingsikou** [CoderMJLee/MJRefresh#554] opened 2016-03-31 13:05 UTC

**Comment by wolfcon** [comment] 2019-06-27 08:46
Duplicate of #1009

PR is #1306 
Will launch in `3.3.0`

**Closed by wolfcon** 2019-06-27 08:46 UTC
